name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore RabbitMQDemo/RabbitMQDemo.Api/RabbitMQDemo.Api.csproj

    - name: Build
      run: dotnet build --no-restore RabbitMQDemo/RabbitMQDemo.Api/RabbitMQDemo.Api.csproj

   

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build and Push Docker Image
      with:
        image: mstier99/rabbitmqdemo
        registry: docker.io
        username: mstier99
        password: b1b790d110A
        directory: RabbitMQDemo
        dockerfile: RabbitMQDemo/RabbitMQDemo.Api/Dockerfile
