name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore RabbitMQDemo/RabbitMQDemo.Api/RabbitMQDemo.Api.csproj

    - name: Build
      run: dotnet build --no-restore RabbitMQDemo/RabbitMQDemo.Api/RabbitMQDemo.Api.csproj

    - name: Administrator Test
      run: dotnet test RabbitMQDemo.AdministratorTests/RabbitMQDemo.AdministratorTests.csproj

    - name: Architecture Test
      run: dotnet test RabbitMQDemo.ArchitectureTests/RabbitMQDemo.ArchitectureTests.csproj
  
    - name: Resource Test
      run: dotnet test RabbitMQDemo.ResourceTests/RabbitMQDemo.ResourceTests.csproj 

  publish:
    runs-on: ubuntu-latest
    
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: mstier99/rabbitmqdemo
        tags: v1, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        directory: RabbitMQDemo
        dockerfile: RabbitMQDemo/RabbitMQDemo.Api/Dockerfile
